[language-server.rust-analyzer.config]
check = { command = "clippy" }
cargo = { allFeatures = true }
 
[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[[language]]
name = "dart"
scope = "source.dart"
injection-regex = "dart"
file-types = ["dart"]
roots = ["pubspec.yaml"]
# comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "dart" ]
auto-format = true

[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs", "lhs", "hs.boot", "lhs.boot"]
roots = ["cabal.project", "stack.yaml", "Setup.hs", "package.yaml"]
comment-token = "--"
indent = { tab-width = 2, unit = "  " }  # this is the important line for manual indent
auto-format = true
formatter = { command = "fourmolu" }  # or "ormolu" if you chose that
language-servers = [ "haskell-language-server" ]

[[language]]
name = "markdown"
language-servers = [ "markdown-oxide" ]  # or "marksman"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"   # essential for don't, it's, you're, etc. â€“ Helix is smart enough not to trigger inside words
'`' = '`'
'<' = '>'   # Hugo/Typora/Quartz shortcodes, also great for <tag> in general
'$' = '$'   # inline math with KaTeX/MathJax (super common in modern Markdown PKM)
'*' = '*'
'_' = '_'
